services:
  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    healthcheck: # Crucial for ensuring DB is ready before app connects
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: ["/bin/sh", "-c", "uvicorn xcnt.asgi:application --host 0.0.0.0 --port 8000 --reload & ./entrypoint.sh && wait"]
    volumes:
      - .:/app  # Live reload on code changes
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: xcnt.settings
    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/expenses/"]
      interval: 30s
      timeout: 10s
      retries: 5

  stream_consumer:
    build:
      context: .
      dockerfile: stream_consumer/Dockerfile
    command: python stream_consumer/consumer.py
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/expenses/"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
